@startuml Spring Boot 声明式事务工作原理

' https://plantuml.com/zh/sequence-diagram

title Spring Boot 声明式事务工作原理

participant "SpringBoot应用" as app
participant TransactionAutoConfiguration
participant EnableTransactionManagementConfiguration
participant CglibAutoProxyConfiguration
participant TransactionManagementConfigurationSelector
participant ProxyTransactionManagementConfiguration
participant TransactionInterceptor

app -> TransactionAutoConfiguration: 启动时自动加载
activate TransactionAutoConfiguration
note right
自动配置类原理
@SpringBootApplication注解中包含@EnableAutoConfiguration
@EnableAutoConfiguration导入AutoConfigurationImportSelector类
AutoConfigurationImportSelector类扫描classpath下的META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports文件
该文件列出了所有的自动配置类
自动配置类注入到IOC容器中逻辑参考AbstractApplicationContext#invokeBeanFactoryPostProcessors
end note

    TransactionAutoConfiguration -> EnableTransactionManagementConfiguration: 扫描内部配置类
    activate EnableTransactionManagementConfiguration

        EnableTransactionManagementConfiguration -> CglibAutoProxyConfiguration: 扫描内部配置类
        activate CglibAutoProxyConfiguration
        note right
        @EnableTransactionManagement生效
        end note

            CglibAutoProxyConfiguration -> TransactionManagementConfigurationSelector: 导入选择器
            activate TransactionManagementConfigurationSelector

                TransactionManagementConfigurationSelector -> ProxyTransactionManagementConfiguration: 导入ProxyTransactionManagementConfiguration
                activate ProxyTransactionManagementConfiguration
                note right
                ProxyTransactionManagementConfiguration及其父类AbstractTransactionManagementConfiguration完成事务基础设施的搭建
                1.注册事务属性解析器AnnotationTransactionAttributeSource
                2.注册事务管理器TransactionManager
                3.注册事务通知TransactionInterceptor
                4.注册事务增强器BeanFactoryTransactionAttributeSourceAdvisor
                5.注册事务事件监听器工厂TransactionalEventListenerFactory
                end note
                ProxyTransactionManagementConfiguration --> TransactionManagementConfigurationSelector
                deactivate ProxyTransactionManagementConfiguration

            TransactionManagementConfigurationSelector --> CglibAutoProxyConfiguration: 
            deactivate TransactionManagementConfigurationSelector

        CglibAutoProxyConfiguration --> EnableTransactionManagementConfiguration:
        deactivate CglibAutoProxyConfiguration

    EnableTransactionManagementConfiguration --> TransactionAutoConfiguration:
    deactivate EnableTransactionManagementConfiguration

TransactionAutoConfiguration --> app:
deactivate TransactionAutoConfiguration

@enduml